// LOCALHOST
###
GET http://localhost:3000/contacts

###

GET http://localhost:3000/contacts/65135b22b03dd75560974441

###
GET http://localhost:3000/contacts/65135b43b03dd75560974442

###
GET http://localhost:3000/contacts/65135b64b03dd75560974443

###
POST http://localhost:3000/contacts HTTP/1.1
content-Type: application/json

{
    "firstName":"Joe",
    "lastName":"Hogg",
    "email":"joehogg@gmail.com",
    "favoriteColor":"Silver",
    "birthday":"02/23/2002"
}

###
PUT http://localhost:3000/contacts/65135b64b03dd75560974443 HTTP/1.1
Content-Type: application/json

{
  "firstName": "Josh",
  "lastName": "Christensen",
  "email": "joshchristensen@gmail.com",
  "favoriteColor": "Blue",
  "birthday": "03/19/97"
}

###
DELETE http://localhost:3000/contacts/6518ced14aa8ab590df39a68 HTTP/1.1

// PRODUCTION Deploy
###
GET https://cse341-tu0r.onrender.com/contacts

###
GET https://cse341-tu0r.onrender.com/contacts/65135b22b03dd75560974441

###
GET https://cse341-tu0r.onrender.com/contacts/65135b43b03dd75560974442

###
GET https://cse341-tu0r.onrender.com/contacts/65135b64b03dd75560974443

###
POST https://cse341-tu0r.onrender.com/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName":"Joe",
    "lastName":"Hogg",
    "email":"joehogg@gmail.com",
    "favoriteColor":"Silver",
    "birthday":"02/23/2002"
}

###
PUT https://cse341-tu0r.onrender.com/contacts/65135b64b03dd75560974443 HTTP/1.1
Content-Type: application/json

{
  "firstName": "Josh",
  "lastName": "Christensen",
  "email": "joshchristensen1@gmail.com",
  "favoriteColor": "Blue",
  "birthday": "03/19/97"
}

###
DELETE https://cse341-tu0r.onrender.com/contacts/6518d9a1a890013d46f5e47d HTTP/1.1